retail_store_dbt:
  outputs:
    dev:
      type: sqlite
      threads: 1
      database: public
      schema: 'main'
      schemas_and_paths:
        main: 'src/retail_store/db/public.db'
      schema_directory: 'src/retail_store/db'
    prod:
      type: sqlite
      threads: 1
      database: public
      schema: 'main'
      schemas_and_paths:
        main: 'src/retail_store/db/public.db'
      schema_directory: 'src/retail_store/db'
  target: dev
